"""
Hybrid API JavaScript generator for MCP Apps.

Generates JavaScript that works both with MCP Apps bridge and REST API fallback.
"""


def generate_hybrid_api_script(
    api_base: str = "http://127.0.0.1:3847",
    enable_hmr: bool = True,
    hmr_interval_ms: int = 2000,
) -> str:
    """
    Generate JavaScript for hybrid MCP Apps / REST API.

    Args:
        api_base: Base URL for REST API fallback
        enable_hmr: Enable hot module replacement polling
        hmr_interval_ms: HMR polling interval in milliseconds

    Returns:
        JavaScript code to include in MCP App HTML
    """
    hmr_code = ""
    if enable_hmr:
        hmr_code = f"""
    // Hot-reload: poll for build changes
    const BUILD_TIME = '{__import__("time").time_ns()}';
    async function checkForReload() {{
      try {{
        const resp = await fetch(API_BASE.replace(':3847', ':3850') + '/health?_=' + Date.now());
        if (resp.ok) {{
          const htmlResp = await fetch(location.href + '?_=' + Date.now(), {{ cache: 'no-store' }});
          const html = await htmlResp.text();
          const match = html.match(/BUILD_TIME = '(\\d+)'/);
          if (match && match[1] !== BUILD_TIME) {{
            console.log('[HMR] Build changed:', BUILD_TIME, '->', match[1]);
            location.reload();
          }}
        }}
      }} catch (e) {{ /* server restarting */ }}
    }}
    setInterval(checkForReload, {hmr_interval_ms});
"""

    return f"""
    // =========================================================================
    // Hybrid MCP Apps API - works with MCP bridge or REST fallback
    // Generated by mcp-sideport
    // =========================================================================

    const API_BASE = '{api_base}';

    // Detect if MCP Apps bridge is available
    const hasMcpBridge = () =>
      window.mcpApps &&
      typeof window.mcpApps.callTool === 'function' &&
      window.mcpApps._hostAvailable !== false;

    /**
     * Call a tool via MCP bridge or REST API fallback.
     * Use for read operations (GET).
     *
     * @param {{string}} toolName - Tool name (e.g., 'getSessions')
     * @param {{object}} args - Tool arguments
     * @param {{string}} apiPath - REST API path fallback (e.g., '/api/sessions')
     * @returns {{Promise<any>}} Tool result
     */
    async function callToolOrApi(toolName, args, apiPath) {{
      if (hasMcpBridge()) {{
        try {{
          return await window.mcpApps.callTool(toolName, args);
        }} catch (e) {{
          console.warn('[Hybrid] MCP bridge failed, falling back to API:', e.message);
        }}
      }}
      const url = new URL(API_BASE + apiPath);
      Object.entries(args || {{}}).forEach(([k, v]) => url.searchParams.set(k, String(v)));
      const resp = await fetch(url);
      return resp.json();
    }}

    /**
     * Execute an action via MCP bridge or REST API fallback.
     * Use for write operations (POST).
     *
     * @param {{string}} action - Action name (e.g., 'spawn_session')
     * @param {{object}} args - Action arguments
     * @returns {{Promise<any>}} Action result
     */
    async function callAction(action, args) {{
      if (hasMcpBridge()) {{
        try {{
          return await window.mcpApps.callTool(action, args);
        }} catch (e) {{
          console.warn('[Hybrid] MCP bridge failed for action, falling back to API:', e.message);
        }}
      }}
      const resp = await fetch(API_BASE + '/api/action', {{
        method: 'POST',
        headers: {{ 'Content-Type': 'application/json' }},
        body: JSON.stringify({{ action, args }}),
      }});
      if (!resp.ok) {{
        const err = await resp.json();
        throw new Error(err.error || 'Action failed');
      }}
      return resp.json();
    }}

    /**
     * Send a log message (only works with MCP bridge).
     *
     * @param {{string}} level - Log level (info, warn, error)
     * @param {{string}} message - Log message
     */
    function sendLog(level, message) {{
      if (hasMcpBridge() && window.mcpApps.sendLog) {{
        window.mcpApps.sendLog(level, message);
      }} else {{
        console[level === 'error' ? 'error' : level === 'warn' ? 'warn' : 'log']('[MCP]', message);
      }}
    }}
{hmr_code}
    // =========================================================================
    // End Hybrid API
    // =========================================================================
"""


def wrap_html_with_hybrid_api(
    html: str,
    api_base: str = "http://127.0.0.1:3847",
    enable_hmr: bool = True,
) -> str:
    """
    Wrap HTML with hybrid API script.

    Inserts the hybrid API script before </body> or at end of HTML.

    Args:
        html: Original HTML content
        api_base: Base URL for REST API fallback
        enable_hmr: Enable hot module replacement

    Returns:
        HTML with hybrid API script injected
    """
    script = f"<script>{generate_hybrid_api_script(api_base, enable_hmr)}</script>"

    if "</body>" in html:
        return html.replace("</body>", f"{script}</body>")
    elif "</html>" in html:
        return html.replace("</html>", f"{script}</html>")
    else:
        return html + script
